### ISSUE TITLE
Set up Kanban Board

### ISSUE THREAD

**Issue by kelvinbush** [kelvinbush/recipe-rails#17]
In this pull request @camilevahviraki and I set up the kanban board and divided the tasks.
Our team consists of 2 members.
Here is our [project](https://github.com/kelvinbush/recipe-rails/projects/1).

**Comment by brytebee** [comment]
Hi Team👋,

##

### Highlights💡 
- Good PR Summary.✔️
- The team member number is stated.✔️
- The link is provided and works fine.✔️
- The Kanban board is correctly set up and cards are fairly divided.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
